### PR TITLE
BLD: replicate local environment.yml for CI

### PR DESCRIPTION
**Pull request by bifbof**
I cannot replicate the build error of #520.
Thus I try to change the `environment.yml` file of the test to see if the error remains.

### CODE REVIEW

**Comment by bifbof** [comment]
Ok this just worked :D
closes #520

**Comment by hongyeehh** [comment]
Ahh great, so the change is to delete the `pandas` dependency and rely on its version requirement in `geopandas`?

**Comment by bifbof** [comment]
> Ahh great, so the change is to delete the `pandas` dependency and rely on its version requirement in `geopandas`?

I think the reason was to move geopandas up in the chain. But to be honest, I neither know what caused this nor what fixed it. I simply copied the `environment.yml` file from the root.

**Comment by hongyeehh** [comment]
Well, anyway, it works. The dependency issue is always a pain :)

**Review by hongyeehh — APPROVED** [review]

**Pull request merged**
