### PR TITLE
BUG: Load extent correctly from postgis

### LINKED ISSUE #365: Bug in reading locations with extent from postgis
I wrote a `locations` table to postgis with the function 
```
locs.as_locations.to_postgis(con=engine, name="locations", ...    )
```
I try to read it with 
```
sql = "SELECT * FROM schema.locations"
locs = ti.io.read_locations_postgis(sql, con=engine, extent="extent")
```
However, the extent is not a geometry in the output `locs`. I had to add the following line to make it work (the problem was the wkb encoding):
```
 locs["extent"] = locs["extent"].apply(lambda x: wkb.loads(bytes.fromhex(x)))
```

So we probably have to include this in the `read_locations_postgis` function. Please let me know if I just overlooked something, or whether I should go ahead with the changes.

### PR DESCRIPTION
**Pull request by bifbof**
Bugfix for reading extent correctly from postgis.
Closes #365

### CODE REVIEW

**Comment by bifbof** [comment]
It seems that we have an unrelated bug. The strange thing is that I cannot reproduce this bug on my local machine.

**Comment by hong2223** [comment]
> It seems that we have an unrelated bug.

Thanks for the PR, I'll take a look at our test error

**Comment by bifbof** [comment]
> Thanks for the PR, I'll take a look at our test error

Nice thanks for the fix.

**Comment by NinaWie** [comment]
Thanks for taking care of this @bifbof! Looks good to me, I already merged it

**Pull request merged**
