### PR TITLE
Add github action to check documentation syntax

### PR DESCRIPTION
**Pull request by rbuffat**
This PR adds a github action that runs rstcheck on each PR or push to the repository. 

rstcheck is a tool to ["Checks syntax of reStructuredText and code blocks nested within it."](https://pypi.org/project/rstcheck/)

### CODE REVIEW

**Comment by henrymartin1** [comment]
Sounds cool, thanks for the PR! So this is basically a quality check for the documentation?
Do we need to add something to the repository?

**Comment by rbuffat** [comment]
> So this is basically a quality check for the documentation?

Yes, basically a CI for the documentation. However, it could be that rstcheck does not support things that are supported by e.g. read the docs. E.g. the autofunction are disabled in the rstcheck command: `--ignore-directives autofunction`

So in the future, there might other things that need to be considered. If the action is more a burden than a help, it can be stopped by simply deleting the yml file. 

> Do we need to add something to the repository?

No, github actions should be enabled by default, and all configurations are contained within the yml file. Once this PR is merged, the action will run for every push or PR.

**Comment by henrymartin1** [comment]
Is there a button for this?

**Comment by rbuffat** [comment]
No, it will show up next to the travis check.

**Pull request merged**
