### PR TITLE
ENH: generalize `_generate_locations_per_user`

### PR DESCRIPTION
**Pull request by bifbof**
I want finally to get rid of these shapely warnings in `preprocessing/staypoints`. 
But for that I want to clean up the method first. I saw that we could easily reuse one function.
So this PR reuses the ``_generate_locations_per_user`` function and refactors there a bit.

### CODE REVIEW

**Review by hong2223 — CHANGES_REQUESTED** [review]
Thanks, I think the simplification is nice.

I only have one comment: you removed the `geo_col` input parameter in the function. I think this related to a geopandas bug we observed [before](https://github.com/mie-lab/trackintel/issues/180#issuecomment-839670952): namely, the geom column cannot be called using `.geometry` after the groupby option. I checked and the [geopandas issue](https://github.com/geopandas/geopandas/issues/1777) is still open. Can you checked if this problem still exist after the change?

**Comment by bifbof** [comment]
> Thanks, I think the simplification is nice.
> 
> I only have one comment: you removed the `geo_col` input parameter in the function. I think this related to a geopandas bug we observed [before](https://github.com/mie-lab/trackintel/issues/180#issuecomment-839670952): namely, the geom column cannot be called using `.geometry` after the groupby option. I checked and the [geopandas issue](https://github.com/geopandas/geopandas/issues/1777) is still open. Can you checked if this problem still exist after the change?

Oh interesting, good catch. I'll write a test and have a look.

**Comment by bifbof** [comment]
So I wrote a little script testing that error and I cannot reproduce it for the `.apply` function.
Here I have a little script to test that.
````python
def fun(gdf):
    print("crs", repr(gdf.geometry.crs))
    print("name", repr(gdf.geometry.name))
    return gdf

world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
world.crs = "EPSG:2056"
world = world.rename(columns={"geometry": "cool_geometry"})
world = world.set_geometry("cool_geometry")
world.groupby("continent").apply(func)
````
It still does not work for `first()` and similar functions that is a bit strange

````python
ret = world.groupby("continent").first()
print(repr(ret.geometry.crs))
````

**Comment by hong2223** [comment]
> So I wrote a little script testing that error and I cannot reproduce it for the `.apply` function. Here I have a little script to test that.
> 
> ```python
> def fun(gdf):
>     print("crs", repr(gdf.geometry.crs))
>     print("name", repr(gdf.geometry.name))
>     return gdf
> 
> world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
> world.crs = "EPSG:2056"
> world = world.rename(columns={"geometry": "cool_geometry"})
> world = world.set_geometry("cool_geometry")
> world.groupby("continent").apply(func)
> ```
> 
> It still does not work for `first()` and similar functions that is a bit strange
> 
> ```python
> ret = world.groupby("continent").first()
> print(repr(ret.geometry.crs))
> ```

What is the status now? Can I understand as the `.geometry` works for some apply functions and failed for others? 

If in general this works for our case I think we can get rid of the "geom" input parameter. This also applies for the input parameter "geo_col" of the "_generate_staypoints_sliding_user()" function

**Comment by bifbof** [comment]
> What is the status now? Can I understand as the `.geometry` works for some apply functions and failed for others?
> 
> If in general this works for our case I think we can get rid of the `geo_col` input parameter. This also applies for the `_generate_staypoints_sliding_user()` function

I would say it works in this case and we can merge it. Functions like `.first()` are implemented in pandas that overrides some geopandas stuff and `.apply()` does not do anything before it is handed to you and then we control it.

**Comment by hong2223** [comment]
> > What is the status now? Can I understand as the `.geometry` works for some apply functions and failed for others?
> > If in general this works for our case I think we can get rid of the `geo_col` input parameter. This also applies for the `_generate_staypoints_sliding_user()` function
> 
> I would say it works in this case and we can merge it. Functions like `.first()` are implemented in pandas that overrides some geopandas stuff and `.apply()` does not do anything before it is handed to you and then we control it.

Thanks! I will merge this after the tests

**Pull request merged**
