### PR TITLE
TST/BLD: Fix ci

### LINKED ISSUE #370: BUG/TST: Github action failed
Our daily GitHub action failed 8 days ago when we had our last pull request. <s>I suspect that some changes from #361 is causing the error.</s>

### PR DESCRIPTION
**Pull request by hong2223**
closes #370.

Basically deleted the requirements of `pandas<=1.2.5`. The test now only includes `python-version: ["3.9"]`, dependency issues still exist for python 3.7.

Two tests would fail with the newer version of pandas. I temporarily commented them out.

### CODE REVIEW

**Comment by hong2223** [comment]
I decided to only include tests with python=3.9 and packages installed from the conda-forge channel. This seems to be used by similar packages

**Comment by bifbof** [comment]
I have a small question regarding this pull request. :)
Why was pygeos removed?

**Comment by hong2223** [comment]
> I have a small question regarding this pull request. :) Why was pygeos removed?

I find pygeos never used in our repo. It is also a required dependency for geopandas that shall be already installed

**Comment by bifbof** [comment]
Ah okay that makes sense, thanks for the answer. Geopandas uses it for io but they didn't included it in their dependencies back then.

**Pull request merged**
